/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.n52.project.enforce.cs4.api;

import java.io.Serializable;
import java.math.BigDecimal;

import org.n52.project.enforce.cs4.model.FeatureCollection;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;

@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2025-12-04T12:19:42.424789700+01:00[Europe/Berlin]",
        comments = "Generator version: 7.13.0")
@Validated
@Tag(
        name = "manorba",
        description = "the manorba API")
public interface ManorbaApi {

    /**
     * POST /cs4_manorba_data : Add a new geo-resource Add/Register a
     * geo-resource dataset for a certain period of time
     *
     * @param body
     *            feature data (required)
     * @return Created (status code 201) or API key is missing or invalid
     *         (status code 401) or Forbidden (status code 403) or Not Found
     *         (status code 404) or Invalid input (status code 405)
     */
    @Operation(
            operationId = "addCs4ManorbaDataAsBody",
            summary = "Add a new geo-resource",
            description = "Add/Register a geo-resource dataset for a certain period of time",
            tags = { "manorba" },
            responses = { @ApiResponse(
                    responseCode = "201",
                    description = "Created"),
                    @ApiResponse(
                            responseCode = "401",
                            description = "API key is missing or invalid",
                            content = { @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = Error.class)) }),
                    @ApiResponse(
                            responseCode = "403",
                            description = "Forbidden",
                            content = { @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = Error.class)) }),
                    @ApiResponse(
                            responseCode = "404",
                            description = "Not Found",
                            content = { @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = Error.class)) }),
                    @ApiResponse(
                            responseCode = "405",
                            description = "Invalid input",
                            content = { @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = Error.class)) }) })
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/cs4_manorba_data",
            produces = { "application/json" },
            consumes = { "application/enforce-cs4-playas-data" })

    ResponseEntity<Serializable> addCs4ManorbaDataAsBody(@Parameter(
            name = "body",
            description = "feature data",
            required = true) @Valid @RequestBody String body);

    /**
     * GET /cs4_manorba_data : get data gathered by the MANORBA app get data
     * gathered by the MANORBA app
     *
     * @param limit
     *            maximum number of requested features (optional)
     * @return OK (status code 200) or Invalid status value (status code 400) or
     *         API key is missing or invalid (status code 401) or Forbidden
     *         (status code 403) or Not Found (status code 404)
     */
    @Operation(
            operationId = "getCs4ManorbaData",
            summary = "get data gathered by the MANORBA app",
            description = "get data gathered by the MANORBA app",
            tags = { "manorba" },
            responses = { @ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = { @Content(
                            mediaType = "application/vnd.geo+json",
                            schema = @Schema(
                                    implementation = FeatureCollection.class)),
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = FeatureCollection.class)) }),
                    @ApiResponse(
                            responseCode = "400",
                            description = "Invalid status value",
                            content = { @Content(
                                    mediaType = "application/vnd.geo+json",
                                    schema = @Schema(
                                            implementation = Error.class)),
                                    @Content(
                                            mediaType = "application/json",
                                            schema = @Schema(
                                                    implementation = Error.class)) }),
                    @ApiResponse(
                            responseCode = "401",
                            description = "API key is missing or invalid",
                            content = { @Content(
                                    mediaType = "application/vnd.geo+json",
                                    schema = @Schema(
                                            implementation = Error.class)),
                                    @Content(
                                            mediaType = "application/json",
                                            schema = @Schema(
                                                    implementation = Error.class)) }),
                    @ApiResponse(
                            responseCode = "403",
                            description = "Forbidden",
                            content = { @Content(
                                    mediaType = "application/vnd.geo+json",
                                    schema = @Schema(
                                            implementation = Error.class)),
                                    @Content(
                                            mediaType = "application/json",
                                            schema = @Schema(
                                                    implementation = Error.class)) }),
                    @ApiResponse(
                            responseCode = "404",
                            description = "Not Found",
                            content = { @Content(
                                    mediaType = "application/vnd.geo+json",
                                    schema = @Schema(
                                            implementation = Error.class)),
                                    @Content(
                                            mediaType = "application/json",
                                            schema = @Schema(
                                                    implementation = Error.class)) }) })
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/cs4_manorba_data",
            produces = { "application/vnd.geo+json", "application/json" })

    ResponseEntity<Serializable> getCs4ManorbaData(@Parameter(
            name = "limit",
            description = "maximum number of requested features",
            in = ParameterIn.QUERY) @Valid @RequestParam(
                    value = "limit",
                    required = false) BigDecimal limit);

}
